version: "3"

services:
  api: 
    build: api
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: frontend
    command: npm run dev
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules
      - /usr/src/app/.next
  db:
    build: db
    container_name: db
    ports: 
      - "6379:6379"
    volumes:
      - ./data:/data