version: "3"

services:
  api: 
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src
      - /usr/src/node_modules
      - /usr/src/app/.next
  db:
    build: ./db
    container_name: db
    ports: 
      - "6379:6379"
    volumes:
      - ./data:/data