version: "3"

services:
  api: 
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frntend
    command: npm run start
    ports:
      - "3000:3000"
  db:
    build: db
    container_name: db
    ports: 
      - "6379:6379"
    volumes:
      - ./data:/data