FROM golang:alpine as builder

RUN mkdir /app

ADD . /app

WORKDIR /app

# Cache & install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy application files
COPY . .

# Install reflex for development
RUN go install github.com/cespare/reflex@latest

# Expose port & start app
EXPOSE 8000
CMD reflex -g '*.go' go run main.go --start-service